stages:
    - test
    - deploy

test:
    stage: test
    only:
        - main
    script:
        - echo run tests in this section

step-deploy.prod:
    stage: deploy
    only:
        - main
    script:
        - apt-get install -y python-pip
        - pip install flask
    environment: production
